### ISSUE TITLE
dp_crypto py not working on my linux mint

### ISSUE THREAD

**Issue by lognozone** [bao7uo/dp_crypto#8]
Hi,

I am using your code from last 7 days. and it working perfectly for me. But from yesterday it is not working 

only loading and loading this options
------------------------------------------
Key position (01) [A]
------------------------------------------
can you please resolve my issue.
Waiting for your response.

Thanks

**Comment by bao7uo** [comment]
There are not enough details for me to help, please open a new issue with more details if you still have an issue.
