### ISSUE TITLE
Recommendations on finding key length?

### ISSUE THREAD

**Issue by VicHarkness** [bao7uo/dp_crypto#9]
Hey, I'm struggling to get a valid result.  When watching the tool run, I never seem to even make it past key position 01.  I've tried turning accuracy down to 5.  Is this a symptom of the target not being vulnerable, or that I have the key length wrong? 

Thanks for reading!

**Comment by bao7uo** [comment]
yes it is likely that the target isn't vulnerable, or the key uses a different key space to the one you choose
